title: Joseph Leedy's Résumé
description: Joseph Leedy's online résumé and portfolio.
url: https://josephleedy.dev

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
theme_skin: ceramic
encoding: "utf-8"
compress-site: yes
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
